pipeline {
  agent any

  stage('Initial cleanUP') {
      steps {
        dir("${WORKSPACE}") {
          deleteDir()
        }
      }
    }

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }


    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }


stage('Package') {
      steps {
        script {
          sh 'echo "Package Stage"'
        }
      }
    }


    stage('Deploy') {
      steps {
        script {
          sh 'echo "Deploy Stage"'
        }
      }
    }

  }
}

